# Generated by Django 4.2.1 on 2023-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='Password_Name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
