# Generated by Django 4.2.1 on 2023-05-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visited_page',
            field=models.CharField(default='', max_length=255),
        ),
    ]
