# Generated by Django 4.2.1 on 2023-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_visitor_visited_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
